#!/bin/bash
SCRIPT_NAME=`basename $0`
BASEDIR=${0/$SCRIPT_NAME/}

if [ -d /package ]; then
	echo "/package already exists, exiting"
	exit
fi

mkdir -p /package/
chmod 1755 /package

if [ ! -d $BASEDIR/admin ]; then
	echo "admin directory not here, exiting"
	exit
fi

echo $BASEDIR/admin
cp -a $BASEDIR/admin /package/
cd /package/admin/daemontools-0.76
package/install
